version: '2'

services:
 
    main:
    #    build: .
    #    image: bigdoods/bimserver
        image: px3l/bimserver
        ports: 
            - 8080
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=8080
            - TOMCAT_USER=xxx
            - TOMCAT_PASSWORD=xxx
        
        networks:
            - front
            - back
            - default
    timer:
        image: bigdoods/timer
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        environment:
            - TIMEOUT=1800000
        networks:
            - default

networks:
    front:
        external:
            name: "puffin_front"

    back:
        external:
            name: "puffin_back"
